const actionTypes = Object.freeze({
    //team
    NEW_TEAM_REQUEST: 'NEW_TEAM_REQUEST',
    NEW_TEAM_SUCCESS: 'NEW_TEAM_SUCCESS',
    NEW_TEAM_FAIL: 'NEW_TEAM_FAIL',

    UPDATE_TEAM_REQUEST: 'UPDATE_TEAM_REQUEST',
    UPDATE_TEAM_SUCCESS: 'UPDATE_TEAM_SUCCESS',
    UPDATE_TEAM_RESET: 'UPDATE_TEAM_RESET',
    UPDATE_TEAM_FAIL: 'UPDATE_TEAM_FAIL',

    DELETE_TEAM_REQUEST: 'DELETE_TEAM_REQUEST',
    DELETE_TEAM_SUCCESS: 'DELETE_TEAM_SUCCESS',
    DELETE_TEAM_RESET: 'DELETE_TEAM_RESET',
    DELETE_TEAM_FAIL: 'DELETE_TEAM_FAIL',

    GET_ALL_TEAMS_REQUEST: 'GET_ALL_TEAMS_REQUEST',
    GET_ALL_TEAMS_SUCCESS: 'GET_ALL_TEAMS_SUCCESS',
    GET_ALL_TEAMS_FAIL: 'GET_ALL_TEAMS_FAIL',

    GET_DETAILS_TEAM_REQUEST: 'GET_DETAILS_TEAM_REQUEST',
    GET_DETAILS_TEAM_SUCCESS: 'GET_DETAILS_TEAM_SUCCESS',
    GET_DETAILS_TEAM_FAIL: 'GET_DETAILS_TEAM_FAIL',

    GET_LOGO_ASSOC_REQUEST: 'GET_LOGO_ASSOC_REQUEST',
    GET_LOGO_ASSOC_SUCCESS: 'GET_LOGO_ASSOC_SUCCESS',
    GET_LOGO_ASSOC_FAIL: 'GET_LOGO_ASSOC_FAIL',


    //stadium
    NEW_STADIUM_REQUEST: 'NEW_STADIUM_REQUEST',
    NEW_STADIUM_SUCCESS: 'NEW_STADIUM_SUCCESS',
    NEW_STADIUM_FAIL: 'NEW_STADIUM_FAIL',

    GET_ALL_STADIUMS_REQUEST: 'GET_ALL_STADIUMS_REQUEST',
    GET_ALL_STADIUMS_SUCCESS: 'GET_ALL_STADIUMS_SUCCESS',
    GET_ALL_STADIUMS_FAIL: 'GET_ALL_STADIUMS_FAIL',


    //groups
    GET_ALL_GROUPS_REQUEST: 'GET_ALL_GROUPS_REQUEST',
    GET_ALL_GROUPS_SUCCESS: 'GET_ALL_GROUPS_SUCCESS',
    GET_ALL_GROUPS_FAIL: 'GET_ALL_GROUPS_FAIL',

    //matchdays
    GET_ALL_MATCHDAYS_REQUEST: 'GET_ALL_MATCHDAYS_REQUEST',
    GET_ALL_MATCHDAYS_SUCCESS: 'GET_ALL_MATCHDAYS_SUCCESS',
    GET_ALL_MATCHDAYS_FAIL: 'GET_ALL_MATCHDAYS_FAIL',

    //match of the team
    GET_MATCH_OF_THE_TEAM_REQUEST: 'GET_MATCH_OF_THE_TEAM_REQUEST',
    GET_MATCH_OF_THE_TEAM_SUCCESS: 'GET_MATCH_OF_THE_TEAM_SUCCESS',
    GET_MATCH_OF_THE_TEAM_FAIL: 'GET_MATCH_OF_THE_TEAM_FAIL',

    NEW_MATCHDAY_REQUEST: 'NEW_MATCHDAY_REQUEST',
    NEW_MATCHDAY_SUCCESS: 'NEW_MATCHDAY_SUCCESS',
    NEW_MATCHDAY_FAIL: 'NEW_MATCHDAY_FAIL',

    //match
    NEW_MATCH_REQUEST: 'NEW_MATCH_REQUEST',
    NEW_MATCH_SUCCESS: 'NEW_MATCH_SUCCESS',
    NEW_MATCH_FAIL: 'NEW_MATCH_FAIL',

    // new details match
    NEW_DETAILS_MATCH_REQUEST: 'NEW_DETAILS_MATCH_REQUEST',
    NEW_DETAILS_MATCH_SUCCESS: 'NEW_DETAILS_MATCH_SUCCESS',
    NEW_DETAILS_MATCH_FAIL: 'NEW_DETAILS_MATCH_FAIL',

    //match
    GET_ALL_MATCHS_REQUEST: 'GET_ALL_MATCHS_REQUEST',
    GET_ALL_MATCHS_SUCCESS: 'GET_ALL_MATCHS_SUCCESS',
    GET_ALL_MATCHS_FAIL: 'GET_ALL_MATCHS_FAIL',

    //get info match by id
    GET_INFO_MATCH_REQUEST: 'GET_INFO_MATCH_REQUEST',
    GET_INFO_MATCH_SUCCESS: 'GET_INFO_MATCH_SUCCESS',
    GET_INFO_MATCH_FAIL: 'GET_INFO_MATCH_FAIL',

    //get details by matchid
    GET_DETAILS_BY_MATCHID_REQUEST: 'GET_DETAILS_BY_MATCHID_REQUEST',
    GET_DETAILS_BY_MATCHID_SUCCESS: 'GET_DETAILS_BY_MATCHID_SUCCESS',
    GET_DETAILS_BY_MATCHID_FAIL: 'GET_DETAILS_BY_MATCHID_FAIL',

    //get detals match
    GET_DETAILS_MATCH_REQUEST: 'GET_DETAILS_MATCH_REQUEST',
    GET_DETAILS_MATCH_SUCCESS: 'GET_DETAILS_MATCH_SUCCESS',
    GET_DETAILS_MATCH_FAIL: 'GET_DETAILS_MATCH_FAIL',

    //new player
    NEW_PLAYER_REQUEST: 'NEW_PLAYER_REQUEST',
    NEW_PLAYER_SUCCESS: 'NEW_PLAYER_SUCCESS',
    NEW_PLAYER_FAIL: 'NEW_PLAYER_FAIL',

    //get player by team
    GET_PLAYERS_OF_TEAM_REQUEST: 'GET_PLAYERS_OF_TEAM_REQUEST',
    GET_PLAYERS_OF_TEAM_SUCCESS: 'GET_PLAYERS_OF_TEAM_SUCCESS',
    GET_PLAYERS_OF_TEAM_FAIL: 'GET_PLAYERS_OF_TEAM_FAIL',

    //get elements
    GET_ELEMENT_REQUEST: 'GET_ELEMENT_REQUEST',
    GET_ELEMENT_SUCCESS: 'GET_ELEMENT_SUCCESS',
    GET_ELEMENT_FAIL: 'GET_ELEMENT_FAIL',

    //get all players
    GET_ALL_PLAYERS_REQUEST: 'GET_ALL_PLAYERS_REQUEST',
    GET_ALL_PLAYERS_SUCCESS: 'GET_ALL_PLAYERS_SUCCESS',
    GET_ALL_PLAYERS_FAIL: 'GET_ALL_PLAYERS_FAIL',

    //get coach
    GET_COACH_REQUEST: 'GET_COACH_REQUEST',
    GET_COACH_SUCCESS: 'GET_COACH_SUCCESS',
    GET_COACH_FAIL: 'GET_COACH_FAIL',


    CLEAR_ERRORS: 'CLEAR_ERRORS',

})

export default actionTypes;